import { useState } from "react";
import {
  ThumbsUp,
  ThumbsDown,
  MoreHorizontal,
  MessageSquare,
} from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const feedbackItems = [
  {
    id: "1",
    client: "Acme Corp",
    agent: "Customer Support Assistant",
    message:
      "The agent was very helpful in resolving my issue with the billing system. It provided clear instructions and followed up to ensure everything was working.",
    rating: "positive",
    date: "2023-07-15",
  },
  {
    id: "2",
    client: "TechStart Inc",
    agent: "Data Analysis Agent",
    message:
      "The quarterly report generated by the agent had some inaccuracies in the sales projections. The data visualization was good, but the numbers need to be double-checked.",
    rating: "negative",
    date: "2023-07-14",
  },
  {
    id: "3",
    client: "Marketing Team",
    agent: "Content Generator",
    message:
      "The social media posts created by the agent were engaging and on-brand. We've seen increased engagement since implementing this agent.",
    rating: "positive",
    date: "2023-07-14",
  },
  {
    id: "4",
    client: "Executive Office",
    agent: "Meeting Scheduler",
    message:
      "The agent sometimes schedules meetings without checking for conflicts with existing appointments. It needs to be more aware of the full calendar.",
    rating: "negative",
    date: "2023-07-13",
  },
  {
    id: "5",
    client: "Dev Team",
    agent: "Code Assistant",
    message:
      "The code optimization suggestions have been incredibly helpful. Our database queries are now 45% faster thanks to the agent's recommendations.",
    rating: "positive",
    date: "2023-07-12",
  },
];

const FeedbackList = () => {
  const [activeTab, setActiveTab] = useState("all");

  const filteredFeedback = feedbackItems.filter((item) => {
    if (activeTab === "all") return true;
    return item.rating === activeTab;
  });

  return (
    <Card className="border bg-transparent">
      <CardHeader>
        <CardTitle>Recent Feedback</CardTitle>
      </CardHeader>
      <CardContent>
        <Tabs defaultValue="all" onValueChange={setActiveTab}>
          <TabsList className="grid w-full grid-cols-3 bg-slate-800/30">
            <TabsTrigger value="all">All</TabsTrigger>
            <TabsTrigger value="positive">Positive</TabsTrigger>
            <TabsTrigger value="negative">Negative</TabsTrigger>
          </TabsList>
          <TabsContent value={activeTab} className="pt-4">
            <div className="space-y-4">
              {filteredFeedback.map((item) => (
                <div key={item.id} className="rounded-lg border p-4">
                  <div className="flex items-start justify-between">
                    <div className="flex items-start gap-4">
                      <Avatar>
                        <AvatarFallback>{item.client.charAt(0)}</AvatarFallback>
                      </Avatar>
                      <div>
                        <div className="flex items-center gap-2">
                          <h4 className="font-medium">{item.client}</h4>
                          <Badge
                            variant={
                              item.rating === "positive"
                                ? "default"
                                : "destructive"
                            }
                            className="ml-2"
                          >
                            {item.rating === "positive" ? (
                              <ThumbsUp className="mr-1 h-3 w-3" />
                            ) : (
                              <ThumbsDown className="mr-1 h-3 w-3" />
                            )}
                            {item.rating}
                          </Badge>
                        </div>
                        <p className="text-sm text-muted-foreground">
                          Agent: {item.agent}
                        </p>
                      </div>
                    </div>
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button variant="ghost" className="h-8 w-8 p-0">
                          <span className="sr-only">Open menu</span>
                          <MoreHorizontal className="h-4 w-4" />
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end">
                        <DropdownMenuLabel>Actions</DropdownMenuLabel>
                        <DropdownMenuItem>
                          <MessageSquare className="mr-2 h-4 w-4" />
                          <span>Respond</span>
                        </DropdownMenuItem>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem>Mark as addressed</DropdownMenuItem>
                        <DropdownMenuItem>Archive</DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>
                  <p className="mt-4 text-sm">{item.message}</p>
                  <p className="mt-2 text-xs text-muted-foreground">
                    {item.date}
                  </p>
                </div>
              ))}
            </div>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
};

export default FeedbackList;
