import { StatCardData } from "@/types";
import {
  Grid2X2,
  Zap,
  Clock,
  Users2Icon,
  CalendarClock,
  ShieldCheck,
  Snowflake,
  Thermometer,
  Calendar,
  FileText,
  TrendingUp,
  Users,
  UserCheck,
  Handshake,
} from "lucide-react";

/**===========================================
 * Stat card data for the admin dashboard.
 ===========================================*/
export const adminDashboardStats: StatCardData[] = [
  {
    value: "--", // Replace with live data
    icon: CalendarClock,
    color: "blue",
    title: "Recent Logins",
    change: "Users logged in today",
  },
  {
    value: "--", // Replace with live data
    icon: Clock,
    color: "cyan",
    title: "Active Sessions",
    change: "Users currently online",
  },
  {
    value: "--", // Replace with live data
    icon: ShieldCheck,
    color: "orange",
    title: "Failed Login Attempts",
    change: "Security metric",
  },
  {
    value: "--", // Replace with live data
    icon: Handshake,
    color: "purple",
    title: "Impersonation Events",
    change: "Admin impersonations this week",
  },
  {
    value: "--", // Replace with live data
    icon: Zap,
    color: "green",
    title: "System Health",
    change: "API/server uptime",
  },
  {
    value: "--", // Replace with live data
    icon: FileText,
    color: "blue",
    title: "Notifications Sent",
    change: "System/user notifications",
  },
  {
    value: "--", // Replace with live data
    icon: TrendingUp,
    color: "orange",
    title: "Content Created",
    change: "Reports/files generated",
  },
  {
    value: "--", // Replace with live data
    icon: Users,
    color: "blue",
    title: "Total Users",
    change: "All users in the system",
  },
  {
    value: "--", // Replace with live data
    icon: Users2Icon,
    color: "purple",
    title: "Total Clients",
    change: "Registered client accounts",
  },
  {
    value: "--", // Replace with live data
    icon: UserCheck,
    color: "green",
    title: "Verified Users",
    change: "Users with verified accounts",
  },
  {
    value: "--", // Replace with live data
    icon: ShieldCheck,
    color: "orange",
    title: "Unverified Users",
    change: "Users pending verification",
  },
  {
    value: "--", // Replace with live data
    icon: FileText,
    color: "orange",
    title: "Pending Accounts",
    change: "Accounts awaiting approval",
  },
  {
    value: "--", // Replace with live data
    icon: ShieldCheck,
    color: "cyan",
    title: "Admin Accounts",
    change: "Total admin users",
  },
  {
    value: "--", // Replace with live data
    icon: Handshake,
    color: "cyan",
    title: "Designer Accounts",
    change: "Total designer users",
  },
  {
    value: "--", // Replace with live data
    icon: Thermometer,
    color: "green",
    title: "Videographer Accounts",
    change: "Total videographer users",
  },
  {
    value: "--", // Replace with live data
    icon: Snowflake,
    color: "blue",
    title: "AI Developer Accounts",
    change: "Total AI developer users",
  },
];

/**============================================
 * Stat card data for the client dashboard.
 ============================================*/
export const clientDashboardStats: StatCardData[] = [
  {
    value: "10",
    icon: Users,
    color: "purple",
    title: "Total Leads",
    change: "Qualified leads generated by AI agents",
  },
  {
    value: "28",
    icon: FileText,
    color: "blue",
    title: "Total Reports",
    change: "AI-generated content pieces this month",
  },
  {
    value: "7",
    icon: Calendar,
    color: "green",
    title: "Appointments Booked",
    change: "Customer appointments scheduled this week",
  },
  {
    value: "68%",
    icon: TrendingUp,
    color: "orange",
    title: "Conversion Rate",
    change: "Lead to appointment conversion rate",
  },
];

/**===================================================
 * Stat card data for the client warm lead dashboard.
 ===================================================*/
export const clientKairoAuditDashboardStats: StatCardData[] = [
  {
    value: "2",
    icon: Users,
    color: "orange",
    title: "Leads Captured",
    change: "+5 from last month",
  },
  {
    value: "73%",
    icon: Calendar,
    color: "blue",
    title: "Booking Rate",
    change: "+14 from last month",
  },
  {
    value: "50%",
    icon: UserCheck,
    color: "green",
    title: "Showup Rate",
    change: "+3 from last month",
  },
  {
    value: "30%",
    icon: Handshake,
    color: "purple",
    title: "Close Rate",
    change: "+2 from last month",
  },
];

/**===================================================
 * Stat card data for the client warm lead dashboard.
 ===================================================*/
export const clientWarmLeadDashboardStats: StatCardData[] = [
  {
    value: "5",
    icon: Users,
    color: "orange",
    title: "Leads Captured",
    change: "+5 from last month",
  },
  {
    value: "73%",
    icon: Calendar,
    color: "blue",
    title: "Booking Rate",
    change: "+14 from last month",
  },
  {
    value: "50%",
    icon: UserCheck,
    color: "green",
    title: "Showup Rate",
    change: "+3 from last month",
  },
  {
    value: "30%",
    icon: Handshake,
    color: "purple",
    title: "Close Rate",
    change: "+2 from last month",
  },
];

/**===================================================
 * Stat card data for the client warm lead dashboard.
 ===================================================*/
export const clientAppointmentDashboardStats: StatCardData[] = [
  {
    value: "28",
    icon: Thermometer,
    color: "orange",
    title: "Warm Leads",
    change: "+5 from last month",
  },
  {
    value: "63",
    icon: Snowflake,
    color: "blue",
    title: "Cold Leads",
    change: "+14 from last month",
  },
  {
    value: "19",
    icon: CalendarClock,
    color: "green",
    title: "Appointments Set",
    change: "+3 from last month",
  },
  {
    value: "11",
    icon: ShieldCheck,
    color: "purple",
    title: "Audits Done",
    change: "+2 from last month",
  },
];
