import { StatCardData } from "@/types";
import {
  Grid2X2,
  Zap,
  Clock,
  Users2Icon,
  CalendarClock,
  ShieldCheck,
  Snowflake,
  Thermometer,
  Calendar,
  FileText,
  TrendingUp,
  Users,
} from "lucide-react";

/**===========================================
 * Stat card data for the admin dashboard.
 ===========================================*/
export const adminDashboardStats: StatCardData[] = [
  {
    value: "14",
    icon: Grid2X2,
    color: "blue",
    title: "Total Leads",
    change: "Warm and Cold Leads",
  },
  {
    value: "20",
    icon: Users2Icon,
    color: "purple",
    title: "Total Clients",
    change: "Clients using Agentic Flow",
  },
  {
    value: "100%",
    color: "green",
    icon: Zap,
    title: "AI-driven",
    change: "Intelligent by design, scalable by nature",
  },
  {
    value: "24/7",
    icon: Clock,
    color: "cyan",
    title: "Operation",
    change: "Proactive monitoring and execution",
  },
];

/**===================================================
 * Stat card data for the admin warm lead dashboard.
 ===================================================*/
export const adminWarmLeadDashboardStats: StatCardData[] = [
  {
    value: "28",
    icon: Thermometer,
    color: "orange",
    title: "Warm Leads",
    change: "+5 from last month",
  },
  {
    value: "63",
    icon: Snowflake,
    color: "blue",
    title: "Cold Leads",
    change: "+14 from last month",
  },
  {
    value: "19",
    icon: CalendarClock,
    color: "green",
    title: "Appointments Set",
    change: "+3 from last month",
  },
  {
    value: "11",
    icon: ShieldCheck,
    color: "purple",
    title: "Audits Done",
    change: "+2 from last month",
  },
];

/**============================================
 * Stat card data for the client dashboard.
 ============================================*/
export const clientDashboardStats: StatCardData[] = [
  {
    value: "23",
    icon: FileText,
    color: "blue",
    title: "Content Created",
    change: "AI-generated content pieces this month",
  },
  {
    value: "47",
    icon: Users,
    color: "purple",
    title: "Total Leads",
    change: "Qualified leads generated by AI agents",
  },
  {
    value: "12",
    icon: Calendar,
    color: "green",
    title: "Appointments Booked",
    change: "Customer appointments scheduled this week",
  },
  {
    value: "68%",
    icon: TrendingUp,
    color: "orange",
    title: "Conversion Rate",
    change: "Lead to appointment conversion rate",
  },
];

/**===================================================
 * Stat card data for the client warm lead dashboard.
 ===================================================*/
export const clientWarmLeadDashboardStats: StatCardData[] = [
  {
    value: "28",
    icon: Thermometer,
    color: "orange",
    title: "Warm Leads",
    change: "+5 from last month",
  },
  {
    value: "63",
    icon: Snowflake,
    color: "blue",
    title: "Cold Leads",
    change: "+14 from last month",
  },
  {
    value: "19",
    icon: CalendarClock,
    color: "green",
    title: "Appointments Set",
    change: "+3 from last month",
  },
  {
    value: "11",
    icon: ShieldCheck,
    color: "purple",
    title: "Audits Done",
    change: "+2 from last month",
  },
];

/**===================================================
 * Stat card data for the client warm lead dashboard.
 ===================================================*/
export const clientAppointmentDashboardStats: StatCardData[] = [
  {
    value: "28",
    icon: Thermometer,
    color: "orange",
    title: "Warm Leads",
    change: "+5 from last month",
  },
  {
    value: "63",
    icon: Snowflake,
    color: "blue",
    title: "Cold Leads",
    change: "+14 from last month",
  },
  {
    value: "19",
    icon: CalendarClock,
    color: "green",
    title: "Appointments Set",
    change: "+3 from last month",
  },
  {
    value: "11",
    icon: ShieldCheck,
    color: "purple",
    title: "Audits Done",
    change: "+2 from last month",
  },
];
